/* eslint-disable max-len, camelcase */

'use strict';

exports.seed = function(knex) {
  return knex('posts').del()
  .then(() => {
    return knex('posts').insert([{
      id: 1,
      content: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fermentum dolor ut dolor iaculis, id hendrerit ex lobortis. Vestibulum gravida at leo nec hendrerit. Nulla dictum, lectus eu malesuada vestibulum, nunc nisl eleifend est, quis faucibus quam nulla at nisl. Pellentesque eu laoreet dolor. Curabitur tristique diam at pulvinar dapibus. Praesent at sem in neque tempus fringilla. Proin sit amet neque finibus, bibendum justo ac, gravida lectus.</p><p>Mauris sed tempor nisi. Ut id gravida leo. Nulla vel quam in velit varius placerat maximus at nunc. In blandit urna orci, in ornare ligula fermentum vel. Proin tincidunt, justo quis varius molestie, nibh eros ornare lacus, eu venenatis urna risus eu risus. Praesent sed lorem a velit placerat tempus. Vivamus ipsum risus, lobortis sed nunc non, sodales dapibus purus. Donec condimentum odio a tortor porta blandit. Suspendisse potenti. Vivamus ex dui, blandit in efficitur sed, facilisis vel nisi.Suspendisse id tellus ante.</p><p> Sed molestie suscipit ligula. Sed vehicula aliquet tristique. In eleifend, quam non efficitur commodo, purus justo consectetur tellus, ut sollicitudin enim nunc a magna. Sed tincidunt neque tortor, ac vehicula ligula pharetra id. Nullam a posuere sem, sed tempus ipsum. Vivamus vitae metus nec felis pretium maximus. Aliquam ullamcorper mattis libero eu maximus. Curabitur id rhoncus velit. Ut ultrices metus quis mauris aliquam, eget fringilla nisi pharetra.</p>'
    }, {
      id: 2,
      content: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fermentum dolor ut dolor iaculis, id hendrerit ex lobortis. Vestibulum gravida at leo nec hendrerit. Nulla dictum, lectus eu malesuada vestibulum, nunc nisl eleifend est, quis faucibus quam nulla at nisl. Pellentesque eu laoreet dolor. Curabitur tristique diam at pulvinar dapibus. Praesent at sem in neque tempus fringilla. Proin sit amet neque finibus, bibendum justo ac, gravida lectus.</p><p>Mauris sed tempor nisi. Ut id gravida leo. Nulla vel quam in velit varius placerat maximus at nunc. In blandit urna orci, in ornare ligula fermentum vel. Proin tincidunt, justo quis varius molestie, nibh eros ornare lacus, eu venenatis urna risus eu risus. Praesent sed lorem a velit placerat tempus. Vivamus ipsum risus, lobortis sed nunc non, sodales dapibus purus. Donec condimentum odio a tortor porta blandit. Suspendisse potenti. Vivamus ex dui, blandit in efficitur sed, facilisis vel nisi.Suspendisse id tellus ante.</p><p> Sed molestie suscipit ligula. Sed vehicula aliquet tristique. In eleifend, quam non efficitur commodo, purus justo consectetur tellus, ut sollicitudin enim nunc a magna. Sed tincidunt neque tortor, ac vehicula ligula pharetra id. Nullam a posuere sem, sed tempus ipsum. Vivamus vitae metus nec felis pretium maximus. Aliquam ullamcorper mattis libero eu maximus. Curabitur id rhoncus velit. Ut ultrices metus quis mauris aliquam, eget fringilla nisi pharetra.</p>'
    }, {
      id: 3,
      content: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fermentum dolor ut dolor iaculis, id hendrerit ex lobortis. Vestibulum gravida at leo nec hendrerit. Nulla dictum, lectus eu malesuada vestibulum, nunc nisl eleifend est, quis faucibus quam nulla at nisl. Pellentesque eu laoreet dolor. Curabitur tristique diam at pulvinar dapibus. Praesent at sem in neque tempus fringilla. Proin sit amet neque finibus, bibendum justo ac, gravida lectus.</p><p>Mauris sed tempor nisi. Ut id gravida leo. Nulla vel quam in velit varius placerat maximus at nunc. In blandit urna orci, in ornare ligula fermentum vel. Proin tincidunt, justo quis varius molestie, nibh eros ornare lacus, eu venenatis urna risus eu risus. Praesent sed lorem a velit placerat tempus. Vivamus ipsum risus, lobortis sed nunc non, sodales dapibus purus. Donec condimentum odio a tortor porta blandit. Suspendisse potenti. Vivamus ex dui, blandit in efficitur sed, facilisis vel nisi.Suspendisse id tellus ante.</p><p> Sed molestie suscipit ligula. Sed vehicula aliquet tristique. In eleifend, quam non efficitur commodo, purus justo consectetur tellus, ut sollicitudin enim nunc a magna. Sed tincidunt neque tortor, ac vehicula ligula pharetra id. Nullam a posuere sem, sed tempus ipsum. Vivamus vitae metus nec felis pretium maximus. Aliquam ullamcorper mattis libero eu maximus. Curabitur id rhoncus velit. Ut ultrices metus quis mauris aliquam, eget fringilla nisi pharetra.</p>'
    }, {
      id: 4,
      content: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fermentum dolor ut dolor iaculis, id hendrerit ex lobortis. Vestibulum gravida at leo nec hendrerit. Nulla dictum, lectus eu malesuada vestibulum, nunc nisl eleifend est, quis faucibus quam nulla at nisl. Pellentesque eu laoreet dolor. Curabitur tristique diam at pulvinar dapibus. Praesent at sem in neque tempus fringilla. Proin sit amet neque finibus, bibendum justo ac, gravida lectus.</p><p>Mauris sed tempor nisi. Ut id gravida leo. Nulla vel quam in velit varius placerat maximus at nunc. In blandit urna orci, in ornare ligula fermentum vel. Proin tincidunt, justo quis varius molestie, nibh eros ornare lacus, eu venenatis urna risus eu risus. Praesent sed lorem a velit placerat tempus. Vivamus ipsum risus, lobortis sed nunc non, sodales dapibus purus. Donec condimentum odio a tortor porta blandit. Suspendisse potenti. Vivamus ex dui, blandit in efficitur sed, facilisis vel nisi.Suspendisse id tellus ante.</p><p> Sed molestie suscipit ligula. Sed vehicula aliquet tristique. In eleifend, quam non efficitur commodo, purus justo consectetur tellus, ut sollicitudin enim nunc a magna. Sed tincidunt neque tortor, ac vehicula ligula pharetra id. Nullam a posuere sem, sed tempus ipsum. Vivamus vitae metus nec felis pretium maximus. Aliquam ullamcorper mattis libero eu maximus. Curabitur id rhoncus velit. Ut ultrices metus quis mauris aliquam, eget fringilla nisi pharetra.</p>'
    },]);
  })
  .then(() => {
    return knex.raw(
      "SELECT setval('posts_id_seq', (SELECT MAX(id) FROM posts));"
    );
  });
};
